name: kikay
description: "Make up"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2

  # Camera & ML Kit
  camera: ^0.11.2
  image_picker: ^1.1.2
  image_cropper: ^10.0.0+1
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0

  # Utilities
  path_provider: ^2.1.1
  path: ^1.8.3
  image: ^4.0.17
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/mobilenet_skintone_final.tflite
    - assets/models/mobilenet_undertone_final.tflite
    - assets/
