// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL77duxr08Ow_ArQyqya5EDno5wFI-Dq4',
    appId: '1:1092747732398:android:6884446adb8848ebf0d43f',
    messagingSenderId: '1092747732398',
    projectId: 'kikay-c23f6',
    storageBucket: 'kikay-c23f6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKuZbF7MtcwMn3htNeeuugAZQCxBNBub4',
    appId: '1:1092747732398:web:dfbe4e207be7be10f0d43f',
    messagingSenderId: '1092747732398',
    projectId: 'kikay-c23f6',
    authDomain: 'kikay-c23f6.firebaseapp.com',
    storageBucket: 'kikay-c23f6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS2wX9DZl5Fi3sX_8UcNNyPB71OsAlPdU',
    appId: '1:1092747732398:ios:5698e746f2341e89f0d43f',
    messagingSenderId: '1092747732398',
    projectId: 'kikay-c23f6',
    storageBucket: 'kikay-c23f6.firebasestorage.app',
    iosBundleId: 'com.example.kikay',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS2wX9DZl5Fi3sX_8UcNNyPB71OsAlPdU',
    appId: '1:1092747732398:ios:e7ab30d433974cf9f0d43f',
    messagingSenderId: '1092747732398',
    projectId: 'kikay-c23f6',
    storageBucket: 'kikay-c23f6.firebasestorage.app',
    iosBundleId: 'com.marian.kikayapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKuZbF7MtcwMn3htNeeuugAZQCxBNBub4',
    appId: '1:1092747732398:web:a643f7a2a6f1f1a4f0d43f',
    messagingSenderId: '1092747732398',
    projectId: 'kikay-c23f6',
    authDomain: 'kikay-c23f6.firebaseapp.com',
    storageBucket: 'kikay-c23f6.firebasestorage.app',
  );

}